---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: virtualbox

platforms:
  - name: instance
    box: generic/centos8
  - name: instance-lts
    box: ubuntu/focal64

provisioner:
  name: ansible
  inventory:
    links:
      group_vars: ../../tests/inventory/group_vars/    
verifier:
  name: ansible
